### ISSUE TITLE
为什么不能上传图片

### ISSUE THREAD

**Issue by H-Lbread** [wangfupeng1988/vue2-wangeditor-demo#2]
初学者 vue2 如何配置上传图片、视频地址？在哪配置

**Comment by wangfupeng1988** [comment]
文档首页，右上角搜索“上传图片”

**Comment by H-Lbread** [comment]
这里上传图片走的接口需要传参为type:jw和files:xxx  ，这个选中的图片的信息怎么获得呢，求教！
![1](https://user-images.githubusercontent.com/61006770/167399974-02e2c915-63af-4c35-84e4-c3afb583ca36.jpg)

**Comment by wangfupeng1988** [comment]
如果你有这类要求，可以使用**自定义上传**，文档里有。
